version: "3.8"

services:
  mysql:
    image: mysql:latest
    restart: always
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: bookstore_db
      MYSQL_USER: brand
      MYSQL_PASSWORD: 1234
    ports:
      - "3307:3306"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    container_name: phpmyadmin-container
    environment:
      PMA_HOST: mysql
    ports:
      - "8880:80"